### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RigaOnTheRocks**
Added a part about firewalls alternatives (Lulu & LittleSnitch).

### CODE REVIEW

**Comment by beerisgood** [comment]
Thanks!

Since both programs are not installable via the AppStore (and I recommend it), I unfortunately cannot adopt the suggestion, since "external" programs tend to reduce security instead of improving it. Anyway, it is better not to let harmful programs run in the first place. 

I already have a small part about firewall. This could be extended - but without external additional programs. 

Gladly further feedback

**Comment by RigaOnTheRocks** [comment]
> Thanks!
> 
> Since both programs are not installable via the AppStore (and I recommend it), I unfortunately cannot adopt the suggestion, since "external" programs tend to reduce security instead of improving it. Anyway, it is better not to let harmful programs run in the first place.
> 
> I already have a small part about firewall. This could be extended - but without external additional programs.
> 
> Gladly further feedback

Thanks for the review, I understand your concerns. I'm not very familiar with the Apple Store but don't they also have issues with monitoring for rogue apps (like the play store) ? The sandbox ability is nice tho. 
Using more apps can bring another threat level, nonetheless I like using multiple control layers on the router and directly on the computer, so firewalls are essential in my case.

Thanks !

**Comment by beerisgood** [comment]
Yes, unfortunately, the Apple Store also has its problems - although less than Google's. 
Nevertheless, an "AppStore only" use is the better choice (even under Windows). 

I have nothing against the general use of a firewall. In this case - a software side, but I recommend the integrated in the system and for really intensive isolation a hardware side firewall. This is of course not intended for a normal end user. 

Regarding the multiple layers of protection: always all well and good, but too much complexity can make the whole thing opaque or even broken. Therefore, it is better to stick to less is more. 

I'll close this for now. If needed, feel free to continue the conversation as a discussion!

**Comment by RigaOnTheRocks** [comment]
> Yes, unfortunately, the Apple Store also has its problems - although less than Google's. Nevertheless, an "AppStore only" use is the better choice (even under Windows).
> 
> I have nothing against the general use of a firewall. In this case - a software side, but I recommend the integrated in the system and for really intensive isolation a hardware side firewall. This is of course not intended for a normal end user.
> 
> Regarding the multiple layers of protection: always all well and good, but too much complexity can make the whole thing opaque or even broken. Therefore, it is better to stick to less is more.
> 
> I'll close this for now. If needed, feel free to continue the conversation as a discussion!

Complexity can surely be a problem, we see that nowadays where people/compagnies use a ton of softwares/infrastructures that are somehow interdependent, and brings a lot of breach possibilities.
But I prefer to have the option to audit what's happening on a computer or a router, unless if the tool is connected to the internet.

**Pull request closed without merging**
